import type { InsightPost } from "./posts";

export const moreInsightPosts: InsightPost[] = [
  {
    slug: "cash-flow-vs-profit-small-business",
    title: "Cash Flow vs. Profit: Why a Profitable Business Can Still Feel Broke",
    description: "Understand the difference between profit and cash flow, and learn what to review when the income statement looks healthy but cash still feels tight.",
    category: "Profit Leaks",
    publishedAt: "2026-09-17",
    readTime: "7 min read",
    takeaway: "Profit measures performance over a period; cash flow measures when money actually enters and leaves the business.",
    sections: [
      { heading: "Profit and cash answer different questions", paragraphs: ["A business can report a profit while cash is tied up in receivables, inventory, debt payments, tax obligations, or large one-time purchases. That does not automatically mean the business is failing; it means timing and cash commitments need their own review.", "Compare the profit-and-loss view with bank movement, receivables, payables, debt service, and upcoming obligations before deciding what is wrong."] },
      { heading: "Where to investigate first", paragraphs: ["Look for customers paying more slowly, bills bunching into the same week, large owner draws, inventory purchases, tax payments, or debt principal that does not appear as an operating expense in the same way."], bullets: ["Accounts receivable aging", "Upcoming vendor obligations", "Debt and financing payments", "Owner distributions", "Inventory or equipment purchases", "Seasonal revenue timing"] },
      { heading: "Create a cash visibility habit", paragraphs: ["Use a rolling cash forecast alongside monthly profitability. The goal is to know what is expected to enter, what must leave, and how much cushion remains before a shortfall becomes urgent."] },
    ],
  },
  {
    slug: "reduce-business-expenses-without-cutting-staff",
    title: "How to Reduce Business Expenses Without Cutting Staff",
    description: "A practical framework for lowering operating costs by fixing waste, rework, overtime, and vendor creep before considering headcount reductions.",
    category: "Business Expenses",
    publishedAt: "2026-09-17",
    readTime: "8 min read",
    takeaway: "Cost reduction should start with avoidable process cost and low-value spending before productive capacity is removed.",
    sections: [
      { heading: "Start with costs that do not create customer value", paragraphs: ["Before touching staffing, identify expenses caused by duplicate work, preventable corrections, unused subscriptions, rushed shipping, avoidable overtime, and vendor pricing that has drifted upward."] },
      { heading: "Rank savings by operational risk", paragraphs: ["A $500 software cut that does not affect service may be safer than reducing labor in a team already missing customer demand. Evaluate each change by dollar impact, implementation effort, customer risk, and reversibility."], bullets: ["Cancel or consolidate unused tools", "Renegotiate recurring vendor contracts", "Reduce rework and repeat visits", "Fix scheduling patterns that create overtime", "Tighten purchasing approval for low-value recurring spend"] },
      { heading: "Measure after the change", paragraphs: ["Compare the next period with the original baseline. A cost reduction is useful only if the business did not create an equal or larger problem somewhere else."] },
    ],
  },
  {
    slug: "small-business-kpi-dashboard",
    title: "How to Build a Small Business KPI Dashboard That Actually Helps",
    description: "Choose a focused set of financial and operating KPIs that help owners see what changed, why it matters, and what to do next.",
    category: "Business KPIs",
    publishedAt: "2026-09-17",
    readTime: "8 min read",
    takeaway: "A useful dashboard highlights decisions, not every number your software can produce.",
    sections: [
      { heading: "Start with the decisions you make repeatedly", paragraphs: ["If you make staffing, pricing, marketing, and purchasing decisions every month, the dashboard should support those decisions. Avoid collecting metrics simply because they are easy to calculate."] },
      { heading: "Use a balanced view", paragraphs: ["Combine outcome measures such as revenue and margin with operational drivers such as conversion, overtime, rework, and customer retention."], bullets: ["Revenue and gross or operating margin", "Labor cost as a share of revenue", "Overtime cost", "Lead conversion or booked-job rate", "Refund or rework rate", "Cash runway or cash balance trend"] },
      { heading: "Add targets and trend", paragraphs: ["A number by itself has little context. Show the target, prior period, current result, and a short explanation of the largest movement."] },
    ],
  },
  {
    slug: "overtime-cost-formula",
    title: "How to Calculate the Real Cost of Overtime",
    description: "Calculate direct overtime cost and review the operating conditions that may be creating recurring overtime pressure.",
    category: "Payroll & Overtime",
    publishedAt: "2026-09-17",
    readTime: "6 min read",
    takeaway: "The overtime premium is only part of the question; recurring overtime can also signal scheduling, demand, training, or process problems.",
    sections: [
      { heading: "Calculate the direct wage cost first", paragraphs: ["Start with overtime hours multiplied by the applicable overtime wage rate. Keep the calculation tied to the same reporting period used for your revenue and labor analysis."] },
      { heading: "Then look for the repeating pattern", paragraphs: ["Break overtime down by employee, shift, day, location, job type, or manager where possible. A concentrated pattern is often more actionable than the total."], bullets: ["Late customer demand", "Call-outs or absence coverage", "Understaffed peak periods", "Poor scheduling", "Rework or repeat jobs", "Training gaps that slow completion"] },
      { heading: "Test one change at a time", paragraphs: ["Change the highest-confidence operational driver, then measure overtime in the next comparable period before claiming a saving."] },
    ],
  },
  {
    slug: "marketing-roi-small-business",
    title: "How to Calculate Marketing ROI for a Small Business",
    description: "Connect marketing spend with qualified leads, sales, contribution margin, and customer value instead of judging campaigns by clicks alone.",
    category: "Marketing ROI",
    publishedAt: "2026-09-17",
    readTime: "8 min read",
    takeaway: "Marketing is productive when it creates enough profitable customer value to justify the acquisition cost.",
    sections: [
      { heading: "Track the path from spend to revenue", paragraphs: ["At minimum, connect campaign spend to leads, qualified leads, customers, revenue, and where possible contribution margin. Surface metrics such as impressions and clicks are useful diagnostics but not the final financial result."] },
      { heading: "Use customer acquisition cost carefully", paragraphs: ["Divide relevant acquisition spend by the number of new customers attributed to that spend. Compare the result with gross profit or contribution expected from those customers rather than revenue alone."] },
      { heading: "Look for channel quality", paragraphs: ["A lower-cost lead source is not better if the leads rarely convert or create low-value customers. Review conversion rate, average order or job value, repeat business, and refund or cancellation rate by channel."] },
    ],
  },
  {
    slug: "customer-acquisition-cost-explained",
    title: "Customer Acquisition Cost Explained for Small Business Owners",
    description: "Learn what CAC measures, what expenses belong in the calculation, and how to compare acquisition cost with customer economics.",
    category: "Marketing ROI",
    publishedAt: "2026-09-17",
    readTime: "6 min read",
    takeaway: "CAC becomes useful when it is compared with the profit generated by acquired customers, not viewed as an isolated number.",
    sections: [
      { heading: "What CAC measures", paragraphs: ["Customer acquisition cost estimates what the business spends to acquire a new customer. A basic version divides acquisition-related sales and marketing spend by new customers acquired in the same period."] },
      { heading: "Be consistent about what you include", paragraphs: ["Depending on the decision, acquisition cost may include advertising, agency fees, sales commissions, marketing software, and dedicated acquisition labor. Document the definition so month-to-month comparisons remain meaningful."] },
      { heading: "Compare CAC with customer value", paragraphs: ["Review first-sale margin, repeat purchases, retention, and service cost. A high CAC can still work if customers are profitable and remain valuable long enough."] },
    ],
  },
  {
    slug: "reduce-rework-costs",
    title: "How to Reduce Rework Costs Without Hurting Quality",
    description: "Find the recurring causes behind corrections, repeat visits, remakes, and do-overs, then measure whether process changes reduce the cost.",
    category: "Profit Leaks",
    publishedAt: "2026-09-17",
    readTime: "7 min read",
    takeaway: "The best rework reduction targets the repeat cause, not the employee or job that happened to expose it.",
    sections: [
      { heading: "Define rework consistently", paragraphs: ["Decide what counts as rework in your operation: repeat visits, remade products, corrected invoices, reopened tickets, returned work, or additional labor caused by an earlier error."] },
      { heading: "Group by root cause", paragraphs: ["Track the reason, not just the cost. Common causes include unclear requirements, missing materials, training gaps, rushed work, poor handoffs, or quality checks that occur too late."] },
      { heading: "Measure cost and recurrence", paragraphs: ["Estimate direct labor and material cost, then watch the frequency after a process change. A reduction that persists across multiple periods is more credible than a one-week improvement."] },
    ],
  },
  {
    slug: "software-subscription-audit",
    title: "How to Audit Business Software and Subscription Costs",
    description: "Identify duplicate, unused, overlapping, and poorly adopted software subscriptions before renewal dates quietly lock in another year of spend.",
    category: "Business Expenses",
    publishedAt: "2026-09-17",
    readTime: "6 min read",
    takeaway: "Software cost control is easier when each tool has an owner, business purpose, usage check, and renewal date.",
    sections: [
      { heading: "Build a complete subscription list", paragraphs: ["Collect tool name, vendor, monthly or annual cost, seats purchased, seats used, owner, renewal date, and primary business purpose."] },
      { heading: "Look for four common problems", paragraphs: ["The easiest savings often come from duplicate tools, unused seats, abandoned trials that became paid plans, and multiple products solving the same job."], bullets: ["Unused licenses", "Duplicate functionality", "Auto-renewals", "Legacy tools after process changes"] },
      { heading: "Review value before renewal", paragraphs: ["Ask the owner what decision, workflow, or revenue process the tool supports. If the answer is unclear, require a short justification before renewal."] },
    ],
  },
  {
    slug: "vendor-spend-analysis",
    title: "Vendor Spend Analysis: How to Find Cost Creep Before It Becomes Normal",
    description: "Review vendor concentration, pricing changes, recurring charges, and contract terms to identify spending that deserves a closer look.",
    category: "Business Expenses",
    publishedAt: "2026-09-17",
    readTime: "7 min read",
    takeaway: "Vendor spend becomes easier to manage when you compare current cost with prior periods, contract expectations, and actual usage.",
    sections: [
      { heading: "Rank vendors by total spend", paragraphs: ["Start with the largest vendors because small percentage changes can create meaningful dollar impact. Then compare current spend with prior periods and expected contract terms."] },
      { heading: "Separate growth from price creep", paragraphs: ["Higher spend can be reasonable when volume, locations, employees, or customer demand increased. Normalize the comparison using units, headcount, transactions, or another relevant activity measure when possible."] },
      { heading: "Prepare for renegotiation", paragraphs: ["Document usage, alternatives, service issues, and upcoming renewal dates. Better preparation creates more negotiating leverage than waiting until the renewal invoice arrives."] },
    ],
  },
  {
    slug: "business-break-even-point",
    title: "How to Calculate Your Business Break-Even Point",
    description: "Estimate the sales level needed to cover fixed and variable costs and use it as a planning tool for pricing, staffing, and growth decisions.",
    category: "Business KPIs",
    publishedAt: "2026-09-17",
    readTime: "7 min read",
    takeaway: "Break-even analysis turns cost structure into a concrete revenue threshold the business can plan around.",
    sections: [
      { heading: "Understand contribution", paragraphs: ["Break-even depends on how much each dollar of revenue contributes after variable costs. The remaining contribution must cover fixed costs before profit begins."] },
      { heading: "Use realistic cost behavior", paragraphs: ["Separate truly fixed costs from costs that rise with sales volume. If labor or fulfillment changes in steps rather than smoothly, model those thresholds explicitly."] },
      { heading: "Use break-even for decisions", paragraphs: ["Test pricing changes, new hires, rent increases, equipment purchases, and seasonal slowdowns against the break-even level before committing."] },
    ],
  },
  {
    slug: "operating-margin-explained",
    title: "Operating Margin Explained: What Small Business Owners Should Watch",
    description: "Understand operating margin, what can move it, and why rising revenue does not guarantee stronger operating performance.",
    category: "Business KPIs",
    publishedAt: "2026-09-17",
    readTime: "6 min read",
    takeaway: "Operating margin helps show how much operating profit remains from revenue after normal operating costs.",
    sections: [
      { heading: "Calculate the margin", paragraphs: ["Operating margin is operating profit divided by revenue, multiplied by 100. Keep the numerator and denominator from the same reporting period."] },
      { heading: "Watch the drivers", paragraphs: ["Margin can fall even while revenue rises if labor, refunds, software, facilities, contractor cost, or acquisition spending grows faster than sales."] },
      { heading: "Investigate movements instead of chasing a benchmark", paragraphs: ["Compare your margin with your own plan and prior periods, then identify which cost or revenue driver explains the change."] },
    ],
  },
  {
    slug: "labor-cost-per-job",
    title: "How to Calculate Labor Cost per Job or Service",
    description: "Measure labor cost at the job, service, or project level so pricing and staffing decisions reflect the work actually required.",
    category: "Payroll & Overtime",
    publishedAt: "2026-09-17",
    readTime: "7 min read",
    takeaway: "Job-level labor visibility helps separate profitable work from services that consume more time than pricing supports.",
    sections: [
      { heading: "Track labor to the work", paragraphs: ["Capture paid hours associated with a job or service and multiply by the relevant labor cost. Decide whether your analysis needs wages only or a fuller burdened labor rate that includes payroll taxes and benefits."] },
      { heading: "Compare with revenue and expected hours", paragraphs: ["Review actual labor cost against job revenue, quoted labor, and expected completion time. Repeated overruns may signal pricing, scope, training, scheduling, or workflow issues."] },
      { heading: "Look for patterns by service type", paragraphs: ["One unprofitable job may be unusual. A service category that repeatedly exceeds expected labor deserves a process or pricing review."] },
    ],
  },
  {
    slug: "employee-productivity-metrics",
    title: "Employee Productivity Metrics That Are Actually Useful",
    description: "Choose productivity measures that connect output, quality, customer value, and labor input without rewarding speed at the expense of outcomes.",
    category: "Business KPIs",
    publishedAt: "2026-09-17",
    readTime: "8 min read",
    takeaway: "Productivity metrics should balance quantity with quality and customer outcomes, not reward volume alone.",
    sections: [
      { heading: "Measure the work that matters", paragraphs: ["Useful productivity measures depend on the role. A technician might be measured by completed jobs and first-time completion, while a support team may use cases resolved, quality, and customer outcomes."] },
      { heading: "Pair speed with quality", paragraphs: ["Any speed metric can create bad incentives if it stands alone. Combine throughput with rework, errors, quality audits, customer satisfaction, or another outcome measure."] },
      { heading: "Use trends for coaching", paragraphs: ["Review individual and team trends over time. Use the metric to identify constraints and training needs rather than treating one number as a complete judgment of performance."] },
    ],
  },
  {
    slug: "monthly-business-review-template",
    title: "What to Review Every Month in Your Business",
    description: "A practical monthly business review covering revenue, margin, labor, expenses, demand, customer outcomes, and the actions that need follow-up.",
    category: "Business KPIs",
    publishedAt: "2026-09-17",
    readTime: "8 min read",
    takeaway: "A monthly review should explain what changed, why it changed, what matters most, and who owns the next action.",
    sections: [
      { heading: "Start with the executive view", paragraphs: ["Review revenue, operating profit or margin, cash position, labor cost, and the largest cost variances. Keep the first page focused on decisions rather than raw detail."] },
      { heading: "Review operating drivers", paragraphs: ["Connect financial outcomes with the activity that created them."], bullets: ["Leads and conversion", "Jobs or transactions", "Average value", "Overtime", "Refunds and rework", "Customer retention or repeat business"] },
      { heading: "Close with actions", paragraphs: ["Assign no more than a few priority actions with an owner, due date, baseline, and success measure. Start the next review by checking whether those actions changed the numbers."] },
    ],
  },
  {
    slug: "forecast-business-expenses",
    title: "How to Forecast Business Expenses Without Overcomplicating It",
    description: "Build a simple expense forecast using known commitments, recent run rates, seasonality, and planned operational changes.",
    category: "Business Expenses",
    publishedAt: "2026-09-17",
    readTime: "7 min read",
    takeaway: "A useful forecast is transparent about assumptions and updated when new information changes the plan.",
    sections: [
      { heading: "Separate known from estimated costs", paragraphs: ["Start with contractual or scheduled costs such as rent, subscriptions, payroll commitments, and debt-related operating charges. Then estimate variable categories using recent activity and expected volume."] },
      { heading: "Document assumptions", paragraphs: ["Write down expected growth, hiring, pricing changes, seasonality, and one-time projects. Forecast quality improves when assumptions are visible enough to challenge."] },
      { heading: "Use scenarios", paragraphs: ["Create a base case plus a downside and upside case for the few assumptions that matter most. This makes the forecast useful for decisions instead of pretending one future is certain."] },
    ],
  },
  {
    slug: "missed-calls-lost-revenue",
    title: "How Missed Calls Can Turn Into Lost Revenue",
    description: "Estimate the business impact of unanswered customer demand using contact volume, qualification, conversion, and average customer value.",
    category: "Profit Leaks",
    publishedAt: "2026-09-17",
    readTime: "7 min read",
    takeaway: "Missed-call opportunity is a model, not guaranteed revenue, so make every assumption visible and testable.",
    sections: [
      { heading: "Model the funnel", paragraphs: ["Start with missed or abandoned contacts. Estimate what portion are genuine prospects, what portion would normally convert, and the average value or contribution of a converted customer."] },
      { heading: "Avoid calling the model guaranteed revenue", paragraphs: ["Not every missed call would have become a sale. Label the result as an opportunity estimate and show the assumptions so owners can replace them with actual business data."] },
      { heading: "Test operational fixes", paragraphs: ["Review peak call windows, callback speed, staffing, routing, self-service, and lead follow-up. Measure actual conversion before and after the change."] },
    ],
  },
  {
    slug: "small-business-data-quality",
    title: "Bad Data Can Create Bad Business Decisions: A Small Business Guide",
    description: "Improve the reliability of analysis by checking dates, categories, duplicates, missing records, and mismatched reporting periods before acting on the results.",
    category: "Business KPIs",
    publishedAt: "2026-09-17",
    readTime: "7 min read",
    takeaway: "The quality of a recommendation cannot be stronger than the data and assumptions used to create it.",
    sections: [
      { heading: "Check the basics first", paragraphs: ["Confirm that revenue, expenses, targets, and operating metrics refer to the same period. Remove duplicates and investigate unusually large or missing values."] },
      { heading: "Use stable categories", paragraphs: ["If the same vendor is classified differently every month, trend analysis becomes noisy. Create simple category rules and apply them consistently."] },
      { heading: "Keep assumptions visible", paragraphs: ["When a metric is estimated rather than observed, label it. Decision-makers should be able to tell the difference between a direct variance and a modeled opportunity."] },
    ],
  },
  {
    slug: "ai-for-small-business-analytics",
    title: "How Small Businesses Can Use AI for Analytics Without Losing Control",
    description: "Use AI to summarize, classify, model, and explain business data while keeping assumptions, source data, and human judgment visible.",
    category: "AI for Small Business",
    publishedAt: "2026-09-17",
    readTime: "8 min read",
    takeaway: "AI is most useful when it accelerates analysis while the business retains visibility into the numbers, assumptions, and decision criteria.",
    sections: [
      { heading: "Use AI for structured support", paragraphs: ["AI can help categorize expenses, summarize patterns, generate questions, draft scenarios, and explain calculations in plain language. Those tasks can save time without handing over the final decision."] },
      { heading: "Keep the source visible", paragraphs: ["For important financial decisions, users should be able to trace a conclusion back to entered data, calculations, or clearly labeled assumptions."] },
      { heading: "Protect sensitive information", paragraphs: ["Before sending business data to any external AI system, understand its privacy controls, retention rules, and organizational permissions. Share only what the task requires."] },
    ],
  },
  {
    slug: "ai-tools-small-business-operations",
    title: "Where AI Tools Can Actually Help Small Business Operations",
    description: "A practical map of AI use cases across customer support, analysis, documentation, forecasting, marketing, and internal workflows.",
    category: "AI for Small Business",
    publishedAt: "2026-09-17",
    readTime: "8 min read",
    takeaway: "The best AI use case removes repetitive work or improves a decision without creating more complexity than it saves.",
    sections: [
      { heading: "Start with repetitive knowledge work", paragraphs: ["Good early use cases include summarizing recurring reports, drafting first-pass customer responses, extracting structured information from documents, categorizing transactions, and generating scenario questions."] },
      { heading: "Measure the operational result", paragraphs: ["Track time saved, error rate, response time, conversion, rework, or another outcome tied to the workflow. A tool that feels impressive but does not improve the process may not justify the cost."] },
      { heading: "Create guardrails", paragraphs: ["Define what data can be shared, when a human review is required, and which decisions cannot rely on generated output alone."] },
    ],
  },
  {
    slug: "business-cost-variance-analysis",
    title: "Cost Variance Analysis for Small Business Owners",
    description: "Compare actual spending with budget or target, identify the largest gaps, and investigate whether the difference is expected, productive, or avoidable.",
    category: "Business Expenses",
    publishedAt: "2026-09-17",
    readTime: "7 min read",
    takeaway: "A variance tells you where reality differed from plan; investigation tells you whether that difference deserves action.",
    sections: [
      { heading: "Calculate the dollar variance", paragraphs: ["Subtract target spending from actual spending for the same category and period. Positive overspend should be reviewed in context rather than automatically labeled waste."] },
      { heading: "Add percentage context", paragraphs: ["Divide the dollar variance by the target when a valid target exists. Percentage movement helps compare categories of different sizes, while dollar impact helps prioritize what matters financially."] },
      { heading: "Investigate before acting", paragraphs: ["Ask whether volume increased, pricing changed, a one-time event occurred, or the additional cost produced revenue or capacity. Then choose the smallest useful action and measure the next period."] },
    ],
  },
  {
    slug: "small-business-profit-improvement-plan",
    title: "How to Build a 30-Day Small Business Profit Improvement Plan",
    description: "Turn financial findings into a focused month-long plan with baselines, owners, actions, and measurable follow-up.",
    category: "Profit Leaks",
    publishedAt: "2026-09-17",
    readTime: "8 min read",
    takeaway: "A short improvement plan works best when it targets a few measurable drivers instead of trying to fix the entire business at once.",
    sections: [
      { heading: "Week 1: Establish the baseline", paragraphs: ["Choose a defined reporting period and document revenue, operating costs, labor, and the two or three largest performance gaps. Confirm the data before setting goals."] },
      { heading: "Weeks 2 and 3: Run focused changes", paragraphs: ["Assign one owner to each action. Examples might include schedule adjustments, subscription cancellations, vendor reviews, follow-up improvements, or rework prevention."] },
      { heading: "Week 4: Measure and decide", paragraphs: ["Compare the follow-up result with the baseline and document what changed. Keep improvements that are supported by the data, modify uncertain experiments, and stop changes that created new problems."] },
    ],
  },
];
