import { ArrowLeft, Calculator, Sparkles } from "lucide-react";

const blocks = [
  { title: "Case Comparisons & Business Questions", body: "Expected case uses your entered forecast scenario. Best case increases each projected month's revenue and decreases scenario costs by the adjustable variation percentages; worst case reverses these changes. These one-time level shocks do not alter monthly growth rates and are not probabilities or statistical confidence intervals. The business question tools calculate monthly target overruns, a fixed 15% revenue decrease with unchanged costs, and the effect of full incremental employment costs with unchanged revenue. They use local calculations, not an external AI model." },
  { title: "1. Actual Vs. Target", body: "For each supported expense category, PulseIQ compares the actual monthly amount you enter with the target, budget, or forecast you enter. A cost overrun is flagged only when actual spending is greater than the target. The difference is treated as a diagnostic opportunity to investigate—not proof that the entire difference can or should be eliminated." },
  { title: "2. Missed-Lead Opportunity", body: "The optional lead model estimates potential opportunity from missed or unanswered contacts using monthly leads × missed-contact rate × conversion rate × average customer value. This is a modeled opportunity, not guaranteed lost revenue. Recovered callbacks, duplicate contacts, capacity limits, lead quality, and fulfillment constraints can reduce the amount actually recoverable." },
  { title: "3. Revenue Target Gap", body: "If a revenue target is provided, PulseIQ shows the shortfall between target and actual revenue separately from cost leakage. Keeping the two measures separate helps reduce double counting and keeps the financial story clearer." },
  { title: "4. Operating Margin", body: "The diagnostic estimates operating profit as entered revenue minus the supported operating-cost categories entered into the tool. The displayed margin is that estimated profit divided by entered revenue. It is not a GAAP financial statement and may exclude taxes, debt service, depreciation, owner compensation, or other items not entered into the diagnostic." },
  { title: "5. Health Score", body: "PulseIQ's health score is a prioritization signal, not a credit rating or industry certification. The current model reduces a 100-point baseline for the size of detected opportunity relative to revenue, revenue-target shortfall, and very low or negative estimated operating margin. The score should always be interpreted alongside the underlying numbers." },
  { title: "6. Recovery Scenarios", body: "Scenario modeling applies a user-selected recovery percentage to the identified monthly opportunity. A 50% scenario, for example, asks what estimated operating profit could look like if half of the modeled opportunity were recovered. It is a planning scenario, not a forecast or promise." },
  { title: "7. Expense Comparison & Review Signals", body: "When itemized expenses span multiple dates, PulseIQ analyzes one selected month at a time; undated expenses have their own group. Month-to-month movement reflects the entries supplied, not automatically improvement or loss. Possible duplicates and repeat charges are surfaced as review signals—not proof of a billing error." },
  { title: "8. Follow-Up & Confirmed Recovery", body: "A tracked cost action records a starting amount, target, planned fix, and a later amount. PulseIQ shows the observed difference and how the gap above the original target changed. Lower spending alone does not prove causation; volume, timing, service mix, and cost shifting can matter. Owners may separately record an amount supported by their own evidence." },
  { title: "9. Monthly Forecasts", body: "Forecasts compound the entered monthly revenue and operating-cost growth rates from the current diagnostic baseline. Scenario payroll changes apply once to payroll plus overtime, and other-cost reductions apply once to the remaining operating categories. The same monthly cost growth then applies to both paths. Cumulative improvement is the sum of scenario profit minus baseline profit; it is not guaranteed savings. Cash starts from opening cash and adds projected operating profit plus the entered monthly net cash adjustments. This simplified cash model assumes same-month collection and payment, and excludes unentered items and timing differences." },
  { title: "10. Historical Trends & Data Quality", body: "Historical growth uses the geometric average monthly rate between the first and last of at least three consecutive, comparable months. These rates are a descriptive starting point, not a statistical prediction or confidence interval. Seasonal patterns, changes in business mix, and missing costs can distort them. Data review uses transparent keyword suggestions for catch-all categories, vendor whitespace and case matching, calendar-date validation, and a same-category, same-month comparison for unusually large charges. Corrections require the owner to apply them. Alerts update in the open workspace; no background notification or financial-account sync is currently provided." },
];

export default function MethodologyPage() {
  return (
    <main className="min-h-screen bg-[#f4efe7] text-[#101010]">
      <header className="border-b border-black/10 px-5 py-4 md:px-8"><div className="mx-auto flex max-w-5xl items-center justify-between gap-4"><a href="/" className="flex items-center gap-3 font-black"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-black text-white"><Sparkles size={18} /></span><span>PulseIQ Operations</span></a><a href="/" className="inline-flex items-center gap-2 text-sm font-black text-black/55 hover:text-black"><ArrowLeft size={16} /> Home</a></div></header>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-5xl">
        <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-black text-white"><Calculator size={21} /></div>
        <p className="mt-8 text-sm font-black uppercase tracking-[0.22em] text-black/35">Transparent Methodology</p>
        <h1 className="mt-3 max-w-4xl text-5xl font-black leading-[1] tracking-tight md:text-7xl">Know Exactly What The Numbers Mean—And What They Do Not.</h1>
        <p className="mt-6 max-w-3xl text-lg leading-8 text-black/58">PulseIQ is designed to make meaningful operational signals easier to see without overstating what the data can prove. The free diagnostic uses transparent rules based on the figures, targets, and assumptions you provide.</p>
        <div className="mt-12 grid gap-5 md:grid-cols-2">{blocks.map((block) => <article key={block.title} className="rounded-[2rem] border border-black/10 bg-white/75 p-7 shadow-sm"><h2 className="text-2xl font-black">{block.title}</h2><p className="mt-4 leading-7 text-black/55">{block.body}</p></article>)}</div>
        <div className="mt-8 rounded-[2rem] bg-black p-7 text-white md:p-9"><p className="text-xs font-black uppercase tracking-[0.2em] text-white/40">Beyond The Diagnostic</p><h2 className="mt-3 text-3xl font-black">The Free Workspace Identifies The Signal. Paid Analysis Investigates The Cause.</h2><p className="mt-5 max-w-3xl leading-7 text-white/60">A paid PulseIQ review can segment relevant data by time, team, location, channel, product, customer type, workflow stage, or other useful dimensions. Recommendations are tied to patterns supported by the supplied data, with assumptions, limitations, and practical next steps stated clearly.</p></div>
        <div className="mt-12 flex flex-wrap gap-3 border-t border-black/10 pt-8 text-sm font-black"><a href="/privacy" className="rounded-full border border-black/15 px-5 py-3 hover:bg-black hover:text-white">Privacy</a><a href="/terms" className="rounded-full border border-black/15 px-5 py-3 hover:bg-black hover:text-white">Terms</a><a href="/request" className="rounded-full bg-black px-5 py-3 text-white">Request An Analysis</a></div>
      </div></section>
    </main>
  );
}
