"use client";

import { useState } from "react";
import { BusinessInputs, money } from "./model";
import { cashDetail, CashDetail, jobDetail, JobDetail, laborDetail, LaborDetail, safeAmount } from "./detail-model";

const initialLabor: LaborDetail = { taxes: 0, benefits: 0, insurance: 0, otherBurden: 0, paidHours: 0, productiveHours: 0 };
const initialCash: CashDetail = { opening: 0, receivablesIncrease: 0, receivablesDecrease: 0, inventoryIncrease: 0, inventoryDecrease: 0, payablesIncrease: 0, payablesDecrease: 0, noncash: 0, principal: 0, equipment: 0, draws: 0, funding: 0 };
const cashFields: [keyof CashDetail, string][] = [["opening", "Opening cash"], ["receivablesIncrease", "Increase in unpaid customer invoices"], ["receivablesDecrease", "Decrease in unpaid customer invoices"], ["inventoryIncrease", "Increase in inventory balance"], ["inventoryDecrease", "Decrease in inventory balance"], ["payablesIncrease", "Increase in unpaid supplier bills"], ["payablesDecrease", "Decrease in unpaid supplier bills"], ["noncash", "Noncash expenses already deducted from profit"], ["principal", "Loan principal paid"], ["equipment", "Capital equipment purchased with cash"], ["draws", "Owner distributions / draws"], ["funding", "New borrowing / owner capital received"]];

function Field({ label, value, onChange }: { label: string; value: number; onChange: (n: number) => void }) {
  return <label className="block text-sm font-semibold text-slate-700">{label}<input type="number" min="0" max="1000000000" step="any" value={value || ""} placeholder="0" onChange={e => onChange(safeAmount(e.target.value))} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-base text-slate-900" /></label>;
}

export default function DetailPanel({ inputs, profit, period }: { inputs: BusinessInputs; profit: number; period: string }) {
  const [labor, setLabor] = useState(initialLabor);
  const [cash, setCash] = useState(initialCash);
  const [jobs, setJobs] = useState<JobDetail[]>([]);
  const [rate, setRate] = useState(0);
  const [bridgeProfit, setBridgeProfit] = useState(profit);
  const [status, setStatus] = useState("");
  const laborResult = laborDetail(inputs.payroll + inputs.overtime, labor);
  const cashResult = cashDetail(bridgeProfit, cash);
  const results = jobs.map(job => ({ job, result: jobDetail(job, rate) }));
  function download() {
    const text = [`PulseIQ detailed review — ${inputs.businessName || "Unnamed business"} — ${period}`, "LABOR", `Entered payroll + overtime: ${money(inputs.payroll + inputs.overtime)}`, ...Object.entries(labor).map(([k, v]) => `${k}: ${v}`), `Fully loaded labor: ${money(laborResult.total)}`, `Cost per paid hour: ${laborResult.paidRate === null ? "Not available" : laborResult.paidRate.toFixed(2)}`, `Cost per productive hour: ${laborResult.productiveRate === null ? "Not available" : laborResult.productiveRate.toFixed(2)}`, "CASH BRIDGE — partial reconciliation using entered figures", `Starting accrual profit: ${money(bridgeProfit)}`, ...cashFields.map(([key, label]) => `${label}: ${money(cash[key])}`), `Estimated cash movement: ${money(cashResult.movement)}`, `Estimated closing cash: ${money(cashResult.closing)}`, "JOBS — contribution before unallocated overhead", `Entered labor rate: ${rate.toFixed(2)}`, ...results.flatMap(({ job, result }) => [job.name || "Unnamed job", `Revenue: ${money(job.revenue)}; planned hours: ${job.plannedHours}; actual hours: ${job.actualHours}; materials: ${money(job.materials)}; other direct costs: ${money(job.otherCosts)}; incremental rework: ${money(job.rework)}`, `Contribution: ${money(result.contribution)}; excess hours cost: ${money(result.extraLabor)}`]), "These separate reviews do not change the monthly scan or its recovery totals. Avoid counting payroll burden, job costs, or cash movements twice. Zero fields may represent missing data. Cash bridge is not a complete statement of cash flows."].join("\n");
    const url = URL.createObjectURL(new Blob([text], { type: "text/plain;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = "pulseiq-detailed-review.txt"; link.click(); URL.revokeObjectURL(url);
  }
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8">
    <p className="text-sm font-semibold uppercase tracking-widest text-blue-700">Detailed review · {period}</p>
    <h2 className="mt-2 text-3xl font-semibold">What sits underneath the monthly totals?</h2>
    <p className="mt-4 leading-7 text-slate-600">Use payroll reports, beginning and ending balance sheets, and job records from the same month. These additional calculations stay separate from the monthly scan. Download this review before leaving; it is not included in saved snapshots or the executive PDF.</p>
    <details open className="mt-6 rounded-xl border border-slate-200 p-5">
      <summary className="cursor-pointer text-xl font-semibold">1. Fully loaded labor cost</summary>
      <p className="mt-3 leading-7 text-slate-600">Payroll plus overtime in your scan is {money(inputs.payroll + inputs.overtime)}. Enter employer costs excluded from that wage total below. Employer payroll taxes, benefits, workers’ compensation, and other employment costs need their own amounts. Include paid leave wages in payroll once; separate overtime only if it is excluded from payroll.</p>
      <div className="mt-5 grid gap-4 sm:grid-cols-2">{([["taxes", "Employer payroll taxes ($)"], ["benefits", "Employer benefits / retirement ($)"], ["insurance", "Workers’ compensation ($)"], ["otherBurden", "Other employer costs, excluding wages ($)"], ["paidHours", "Total paid hours, including overtime"], ["productiveHours", "Productive hours within paid hours"]] as [keyof LaborDetail, string][]).map(([key, label]) => <Field key={key} label={label} value={labor[key]} onChange={n => setLabor(s => ({ ...s, [key]: n }))} />)}</div>
      <div aria-live="polite" className="mt-5 rounded-xl bg-blue-50 p-4 leading-7"><p>Employer burden: <strong>{money(laborResult.burden)}</strong> · Fully loaded labor: <strong>{money(laborResult.total)}</strong></p><p>Cost per paid hour: <strong>{laborResult.paidRate === null ? "Enter paid hours" : `$${laborResult.paidRate.toFixed(2)}`}</strong> · Cost per productive hour: <strong>{laborResult.productiveRate === null ? "Enter valid hours" : `$${laborResult.productiveRate.toFixed(2)}`}</strong></p></div>
      {laborResult.invalidHours ? <p role="alert" className="mt-3 text-amber-800">Productive hours cannot exceed total paid hours. Check the period and hour totals.</p> : null}
      <p className="mt-3 text-sm leading-6 text-slate-600">To include these costs in the monthly scan, enter them once in your expense records or an appropriate monthly cost category. This labor breakdown can include costs already listed elsewhere in the scan; it does not add them again.</p>
    </details>
    <details className="mt-5 rounded-xl border border-slate-200 p-5">
      <summary className="cursor-pointer text-xl font-semibold">2. Why profit and cash differ</summary>
      <p className="mt-3 leading-7 text-slate-600">Start with accrual-based profit from your books, then compare beginning and ending balances. Enter either the increase or decrease for each balance, not both. Use inventory balance movement here, not total inventory purchases. Principal, capital purchases, and distributions belong in this bridge when they were not already deducted from starting profit.</p>
      <label className="mt-5 block text-sm font-semibold text-slate-700">Accrual profit / loss for the month ($)<input type="number" step="any" min="-1000000000" max="1000000000" value={bridgeProfit} onChange={e => { const n = Number(e.target.value); setBridgeProfit(Number.isFinite(n) ? Math.max(-1e9, Math.min(1e9, n)) : 0); }} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-base" /></label>
      <button type="button" onClick={() => setBridgeProfit(profit)} className="mt-3 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold">Use current scan profit ({money(profit)})</button>
      <p className="mt-3 text-sm leading-6 text-slate-600">The initial value comes from the scan. Replace it if your books use accrual accounting or contain expenses missing from the scan. A cash-basis profit figure is not a suitable starting point for these working-capital adjustments.</p>
      <div className="mt-5 grid gap-4 sm:grid-cols-2">{cashFields.map(([key, label]) => <Field key={key} label={`${label} ($)`} value={cash[key]} onChange={n => setCash(s => ({ ...s, [key]: n }))} />)}</div>
      {([["receivablesIncrease", "receivablesDecrease"], ["inventoryIncrease", "inventoryDecrease"], ["payablesIncrease", "payablesDecrease"]] as [keyof CashDetail, keyof CashDetail][]).some(([a, b]) => cash[a] > 0 && cash[b] > 0) ? <p role="alert" className="mt-3 text-amber-800">Both increase and decrease are entered for a balance. Use its net movement for this month.</p> : null}
      <div aria-live="polite" className="mt-5 rounded-xl bg-slate-900 p-5 leading-7 text-white"><p>Working-capital cash effect: <strong>{money(cashResult.workingCapital)}</strong></p><p>Principal, capital purchases, and draws: <strong>{money(cashResult.outflows)}</strong></p><p>Estimated cash movement: <strong>{money(cashResult.movement)}</strong> · Estimated closing cash: <strong>{money(cashResult.closing)}</strong></p></div>
      <p className="mt-3 text-sm leading-6 text-slate-600">Compare estimated closing cash with your actual bank balance. Unentered taxes, accruals, asset sales, other balances, and timing differences can leave a gap. This partial bridge is not a complete statement of cash flows; these movements are not automatically waste or recoverable savings.</p>
    </details>
    <details className="mt-5 rounded-xl border border-slate-200 p-5">
      <summary className="cursor-pointer text-xl font-semibold">3. Small differences across individual jobs</summary>
      <p className="mt-3 leading-7 text-slate-600">Enter a consistent fully loaded hourly labor rate, then compare each job’s planned and actual hours. Contribution is revenue less entered direct costs, before unallocated overhead. Rework should contain only extra costs not already in actual labor hours, materials, or other direct costs.</p>
      <div className="mt-5"><Field label="Fully loaded hourly labor rate ($)" value={rate} onChange={setRate} /><button type="button" disabled={laborResult.paidRate === null} onClick={() => setRate(laborResult.paidRate || 0)} className="mt-3 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold disabled:opacity-50">Use calculated cost per paid hour</button></div>
      <div className="mt-5 space-y-5">{results.map(({ job, result }, i) => <article key={job.id} className="rounded-xl bg-slate-50 p-4"><label className="block text-sm font-semibold">Job name / reference<input value={job.name} maxLength={100} onChange={e => setJobs(s => s.map(j => j.id === job.id ? { ...j, name: e.target.value } : j))} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-base" placeholder={`Job ${i + 1}`} /></label><div className="mt-4 grid gap-4 sm:grid-cols-2">{([["revenue", "Job revenue ($)"], ["plannedHours", "Planned labor hours"], ["actualHours", "Actual labor hours, including repeat work"], ["materials", "Actual materials ($)"], ["otherCosts", "Other direct costs ($)"], ["rework", "Additional rework costs not entered above ($)"]] as [Exclude<keyof JobDetail, "id" | "name">, string][]).map(([key, label]) => <Field key={key} label={label} value={job[key]} onChange={n => setJobs(s => s.map(j => j.id === job.id ? { ...j, [key]: n } : j))} />)}</div><p className="mt-4 leading-7">Contribution: <strong>{money(result.contribution)}</strong> · Margin: {result.margin === null ? "Enter revenue" : `${result.margin.toFixed(1)}%`} · Excess-hours cost: <strong>{money(result.extraLabor)}</strong></p><button type="button" onClick={() => setJobs(s => s.filter(j => j.id !== job.id))} className="mt-3 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold">Remove job</button></article>)}</div>
      <button type="button" disabled={jobs.length >= 100} onClick={() => setJobs(s => [...s, { id: crypto.randomUUID(), name: "", revenue: 0, plannedHours: 0, actualHours: 0, materials: 0, otherCosts: 0, rework: 0 }])} className="mt-5 rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white disabled:opacity-50">Add job ({jobs.length}/100)</button>
      {jobs.length > 0 ? <p aria-live="polite" className="mt-4 rounded-xl bg-blue-50 p-4 leading-7">Across {jobs.length} entered jobs: contribution <strong>{money(results.reduce((sum, r) => sum + r.result.contribution, 0))}</strong>; excess-hours cost <strong>{money(results.reduce((sum, r) => sum + r.result.extraLabor, 0))}</strong>. Excess-hours cost is already part of actual labor cost; do not add it again. {rate === 0 ? "Enter an hourly rate before interpreting job margins." : "Review repeated overruns by crew, service type, or job before changing pricing or staffing."}</p> : null}
    </details>
    <div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={download} className="rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white">Download detailed review</button><button type="button" onClick={() => { setLabor(initialLabor); setCash(initialCash); setJobs([]); setRate(0); setBridgeProfit(profit); setStatus("Detailed review cleared."); }} className="rounded-xl border border-slate-200 px-5 py-3 font-semibold">Clear detailed review</button></div>
    <p role="status" className="mt-3 text-sm text-slate-600">{status}</p>
  </section>;
}
