"use client";

import { useEffect, useMemo, useState } from "react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, ArrowRight, Download, ShieldCheck, TrendingUp } from "lucide-react";
import { analyzeBusiness, BusinessInputs, costCategories, money } from "./model";
import { ExpenseEntry } from "./expenses";
import { compareForecastCases, defaultForecast, ForecastSettings, HistoryMonth, historyTrend, normalizeForecast, normalizeHistory, projectBusiness } from "./forecast";
import { inspectExpenses } from "./quality";
import type { ReportPlan } from "./pdf-report";
import { forecastMonth, reportingMonth } from "./period";
import { businessKey } from "./recovery";

function Control({ label, value, min, max, onChange, hint }: { label: string; value: number; min: number; max: number; onChange: (n: number) => void; hint?: string }) {
  return <label className="block text-sm font-bold"><span>{label}</span><input className="mt-2 block w-full rounded-xl border border-slate-900/15 bg-white p-3 text-base" type="number" min={min} max={max} step="any" value={value} onChange={e => onChange(Math.max(min, Math.min(max, Number(e.target.value) || 0)))} />{hint ? <span className="mt-2 block font-normal leading-5 text-slate-600">{hint}</span> : null}</label>;
}

export default function PlanningPanel({ inputs, expenses, onUpdateExpense, onPlanChange }: { inputs: BusinessInputs; expenses: ExpenseEntry[]; onUpdateExpense: (id: string, patch: Partial<ExpenseEntry>) => void; onPlanChange: (plan: ReportPlan) => void }) {
  const [settings, setSettings] = useState<ForecastSettings>(defaultForecast);
  const [revenueSwing, setRevenueSwing] = useState(15);
  const [costSwing, setCostSwing] = useState(5);
  const [question, setQuestion] = useState<"spending" | "drop" | "hire">("spending");
  const [hireCost, setHireCost] = useState(0);
  const [history, setHistory] = useState<HistoryMonth[]>([]);
  const [month, setMonth] = useState("");
  const [historicalRevenue, setHistoricalRevenue] = useState(0);
  const [historicalExpenses, setHistoricalExpenses] = useState(0);
  const [message, setMessage] = useState("");
  const [activeTab, setActiveTab] = useState<"predict" | "quality">("predict");
  const projection = useMemo(() => projectBusiness(inputs, settings), [inputs, settings]);
  const cases = useMemo(() => compareForecastCases(inputs, settings, revenueSwing, costSwing), [inputs, settings, revenueSwing, costSwing]);
  const analysis = useMemo(() => analyzeBusiness(inputs, 0), [inputs]);
  const findings = useMemo(() => inspectExpenses(expenses), [expenses]);
  const trend = useMemo(() => historyTrend(history), [history]);
  useEffect(() => { onPlanChange({ settings, revenueSwing, costSwing }); }, [settings, revenueSwing, costSwing, onPlanChange]);
  const update = (key: keyof ForecastSettings, value: number) => setSettings(s => normalizeForecast({ ...s, [key]: value }));
  const storageKey = `pulseiq:planning:v1:${businessKey(inputs.businessName)}`;
  function save() {
    if (!inputs.businessName.trim()) { setMessage("Add a business name before saving this plan."); return; }
    try { localStorage.setItem(storageKey, JSON.stringify({ settings, history, revenueSwing, costSwing })); setMessage("Plan saved for this business in this browser."); }
    catch { setMessage("Your browser could not save the plan. Download the forecast to keep a copy."); }
  }
  function load() {
    if (!inputs.businessName.trim()) { setMessage("Add a business name before loading a plan."); return; }
    try {
      const raw = localStorage.getItem(storageKey);
      if (!raw) { setMessage("No saved plan for this business in this browser."); return; }
      const plan = JSON.parse(raw);
      setSettings(normalizeForecast(plan.settings)); setRevenueSwing(Number.isFinite(plan.revenueSwing) ? Math.min(50, Math.max(0, plan.revenueSwing)) : 15); setCostSwing(Number.isFinite(plan.costSwing) ? Math.min(50, Math.max(0, plan.costSwing)) : 5); setHistory(normalizeHistory(plan.history)); setMessage("Saved plan loaded.");
    } catch { setMessage("The saved plan could not be loaded."); }
  }
  function download() {
    const header = "month,revenue,baseline_costs,scenario_costs,baseline_profit,scenario_profit,baseline_cash,scenario_cash";
    const csv = [header, ...projection.rows.map(r => [r.month, r.revenue, r.baseCosts, r.scenarioCosts, r.baseProfit, r.scenarioProfit, r.baseCash, r.scenarioCash].join(","))].join("\n");
    const caseCsv = ["case,month,revenue,costs,profit,cash", ...cases.flatMap(c => c.rows.map(r => [c.name, r.month, r.revenue, r.costs, r.profit, r.cash].join(",")))].join("\n");
    const assumptions = `PulseIQ planning scenario\nBusiness: ${inputs.businessName || "Unnamed business"}\nBaseline period: ${inputs.reportingPeriod}\nRevenue growth per month: ${settings.revenueGrowth}%\nCost growth per month: ${settings.expenseGrowth}%\nOne-time payroll + overtime change: ${settings.payrollChange}%\nOther-cost reduction: ${settings.costReduction}%\nOpening cash: ${settings.openingCash}\nMonthly net cash adjustments: ${settings.monthlyCashAdjustments}\nCash assumes revenue collected and costs paid in the same month. Taxes, debt service, timing and other unentered items are excluded. This is an assumption-based scenario, not a guaranteed prediction.\n\n${csv}\n\nCase comparison: one-time revenue +/-${revenueSwing}%, costs -/+${costSwing}% versus the scenario in every month. These are stress tests, not probabilities or confidence intervals.\n${caseCsv}`;
    const url = URL.createObjectURL(new Blob([assumptions], { type: "text/plain;charset=utf-8" }));
    const a = document.createElement("a"); a.href = url; a.download = "pulseiq-forecast.txt"; a.click(); URL.revokeObjectURL(url);
  }
  const last = projection.rows[projection.rows.length - 1];
  return <section id="planning" className="mx-auto max-w-7xl rounded-2xl border border-slate-900/10 bg-white p-5 shadow-sm md:p-8">
    <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-widest text-slate-600">Diagnose → Predict → Optimize</p><h2 className="mt-3 text-3xl font-semibold">Make the next decision.</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Check the records behind your results, then test what the coming months could look like.</p></div><a className="inline-flex items-center gap-2 rounded-xl border border-slate-900/15 px-4 py-3 text-sm font-bold" href="#results">View priority actions <ArrowRight size={16} /></a></div>
    {!reportingMonth(inputs.reportingPeriod) ? <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm leading-6">Choose a specific reporting month, such as August 2026, to show calendar dates. Until then, the outlook uses relative month numbers.</p> : <p className="mt-5 text-sm text-slate-600">Forecast begins {forecastMonth(inputs.reportingPeriod, 1)}, following the {inputs.reportingPeriod} baseline.</p>}
    <div role="tablist" aria-label="Planning tools" className="mt-6 flex flex-wrap gap-2">{([{ id: "predict", label: "Forecast & scenarios" }, { id: "quality", label: `Data review (${findings.length})` }] as const).map(tab => <button key={tab.id} role="tab" id={`tab-${tab.id}`} aria-selected={activeTab === tab.id} aria-controls={`panel-${tab.id}`} tabIndex={activeTab === tab.id ? 0 : -1} onKeyDown={e => { if (["ArrowLeft", "ArrowRight", "Home", "End"].includes(e.key)) { e.preventDefault(); const next = e.key === "Home" ? "predict" : e.key === "End" ? "quality" : activeTab === "predict" ? "quality" : "predict"; setActiveTab(next); document.getElementById(`tab-${next}`)?.focus(); } }} onClick={() => setActiveTab(tab.id)} className={`rounded-xl px-5 py-3 text-sm font-bold ${activeTab === tab.id ? "bg-slate-900 text-white" : "border border-slate-900/15 bg-white"}`}>{tab.label}</button>)}</div>
    <div id="panel-quality" role="tabpanel" aria-labelledby="tab-quality" hidden={activeTab !== "quality"} className="mt-6">
      <p className="leading-7 text-slate-600">Suggestions use transparent category rules and transaction comparisons. Nothing is changed or deleted without your review. Duplicate-charge prompts remain in the expense section.</p>
      {!expenses.length ? <div className="mt-5 rounded-2xl bg-slate-50 p-6"><ShieldCheck /><p className="mt-3 font-bold">Add or import itemized expenses to check their quality.</p><p className="mt-2 text-slate-600">Monthly category totals do not contain vendor, date, or invoice detail.</p></div> : !findings.length ? <p className="mt-5 rounded-2xl bg-emerald-50 p-5 font-bold">No issues detected by these checks. This does not verify that your books are complete.</p> : <div className="mt-5 grid gap-3 md:grid-cols-2">{findings.slice(0, 30).map(f => {
        const entry = expenses.find(e => e.id === f.entryId)!;
        const category = costCategories.find(c => c.id === f.suggestedCategory);
        return <article key={f.id} className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="font-semibold">{f.title}</p><p className="mt-2 text-sm font-bold">{entry.vendor || "Unnamed vendor"} · {money(entry.amount)} · {entry.date || "No date"}</p><p className="mt-2 text-sm leading-6 text-slate-600">{f.detail}</p>{f.suggestedCategory || f.suggestedVendor ? <button className="mt-4 rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white" onClick={() => { onUpdateExpense(f.entryId, f.suggestedCategory ? { category: f.suggestedCategory } : { vendor: f.suggestedVendor }); setMessage("Correction applied to the expense. The spending analysis has updated."); }}>Apply {category?.name || "vendor correction"}</button> : <a href="#expense-entry" className="mt-3 inline-block text-sm font-bold underline">Review in expense entries</a>}</article>;
      })}</div>}{findings.length > 30 ? <p className="mt-4 text-sm">Showing 30 of {findings.length} checks. Resolve these to see the remaining issues.</p> : null}
    </div>
    <div id="panel-predict" role="tabpanel" aria-labelledby="tab-predict" hidden={activeTab !== "predict"} className="mt-6">
      <div className="grid gap-7">
        <div className="rounded-2xl bg-slate-50 p-5"><h3 className="text-xl font-semibold">Your assumptions</h3><p className="mt-3 text-sm leading-6 text-slate-600">Starts from the revenue and operating costs currently included in your diagnostic. Growth compounds monthly; payroll changes and cost reductions apply once, from Month 1.</p>
          <label className="mt-5 block text-sm font-bold">Forecast horizon<select aria-label="Forecast horizon" value={settings.horizon} onChange={e => update("horizon", Number(e.target.value))} className="mt-2 w-full rounded-xl border border-slate-900/15 bg-white p-3">{[3, 6, 12].map(n => <option key={n} value={n}>{n} months</option>)}</select></label>
          <div className="mt-4 grid gap-4 sm:grid-cols-2"><Control label="Revenue growth per month (%)" value={settings.revenueGrowth} min={-50} max={50} onChange={n => update("revenueGrowth", n)} /><Control label="Operating cost growth per month (%)" value={settings.expenseGrowth} min={-50} max={50} onChange={n => update("expenseGrowth", n)} /><Control label="Payroll + overtime change (%)" value={settings.payrollChange} min={-100} max={100} onChange={n => update("payrollChange", n)} hint="Example: 8 adds 8%; −8 reduces 8%." /><Control label="Reduce other operating costs (%)" value={settings.costReduction} min={0} max={100} onChange={n => update("costReduction", n)} hint="Excludes payroll and overtime; includes all other entered categories." /><Control label="Opening cash ($)" value={settings.openingCash} min={0} max={1e9} onChange={n => update("openingCash", n)} /><Control label="Monthly net cash adjustments ($)" value={settings.monthlyCashAdjustments} min={-1e9} max={1e9} onChange={n => update("monthlyCashAdjustments", n)} hint="Add financing or subtract debt payments, taxes, and other cash movements excluded above." /></div>
          <div className="mt-5 flex flex-wrap gap-2"><button className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white" onClick={save}>Save plan</button><button className="rounded-xl border border-slate-900/15 px-4 py-2 text-sm font-bold" onClick={load}>Load plan</button><button className="rounded-xl border border-slate-900/15 px-4 py-2 text-sm font-bold" onClick={() => { setSettings(defaultForecast); setMessage("Assumptions reset. Historical rows retained."); }}>Reset assumptions</button></div>
        </div>
        <div className="min-w-0">
          {!projection.ready ? <div className="rounded-2xl bg-slate-50 p-6"><TrendingUp /><h3 className="mt-4 text-xl font-semibold">Enter monthly revenue to start forecasting.</h3><p className="mt-3 leading-7 text-slate-600">Add complete operating costs before interpreting profit or cash. The demo can help you explore the tools.</p></div> : <>
            <div className="grid gap-3 sm:grid-cols-3">{[{ label: `${forecastMonth(inputs.reportingPeriod, settings.horizon)} profit`, value: money(last.scenarioProfit) }, { label: "Scenario profit change", value: money(projection.totalImprovement) }, { label: `${forecastMonth(inputs.reportingPeriod, settings.horizon)} cash`, value: money(last.scenarioCash) }].map(stat => <div key={stat.label} className="rounded-2xl bg-[#0f172a] p-5 text-white"><p className="text-sm text-white/80">{stat.label}</p><p className="mt-3 text-2xl font-semibold">{stat.value}</p></div>)}</div>
            <p className="mt-3 text-sm text-slate-600">Scenario profit change is cumulative over {settings.horizon} months versus the baseline. It excludes implementation costs unless you enter them.</p>
            <div className="mt-5 rounded-2xl border border-slate-900/10 p-3 md:p-5"><h3 className="mb-5 text-xl font-semibold">Revenue versus operating costs</h3><div className="h-[300px] w-full" role="img" aria-label="Projected revenue, baseline costs, and scenario costs. Exact values appear in the table below."><ResponsiveContainer width="100%" height="100%"><LineChart data={projection.rows} margin={{ left: 0, right: 8 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 12 }} minTickGap={30} /><YAxis width={68} tickFormatter={n => `$${Math.round(n / 1000)}k`} tick={{ fontSize: 12 }} /><Tooltip formatter={value => money(Number(value))} /><Legend wrapperStyle={{ fontSize: 14 }} /><Line name="Revenue" type="linear" dataKey="revenue" stroke="#047857" strokeWidth={3} dot={false} isAnimationActive={false} /><Line name="Baseline costs" type="linear" dataKey="baseCosts" stroke="#be123c" strokeWidth={2} strokeDasharray="5 4" dot={false} isAnimationActive={false} /><Line name="Scenario costs" type="linear" dataKey="scenarioCosts" stroke="#2563eb" strokeWidth={3} dot={false} isAnimationActive={false} /></LineChart></ResponsiveContainer></div></div>
            <div aria-live="polite" className="mt-5 space-y-3">{projection.firstLoss ? <p className="rounded-2xl border border-amber-200 bg-amber-50 p-4 leading-6"><AlertTriangle className="mr-2 inline" size={18} /><strong>Baseline operating loss in {forecastMonth(inputs.reportingPeriod, projection.firstLoss)}.</strong> Projected costs exceed revenue under the growth assumptions entered.</p> : <p className="rounded-2xl bg-emerald-50 p-4 leading-6">Baseline revenue covers entered operating costs throughout this horizon.</p>}{projection.firstCashShortfall ? <p className="rounded-2xl border border-red-200 bg-red-50 p-4 leading-6"><strong>Scenario cash shortfall in {forecastMonth(inputs.reportingPeriod, projection.firstCashShortfall)}.</strong> Review opening cash, collection timing, cost changes, and cash adjustments.</p> : null}</div>
            <div className="mt-5 overflow-x-auto rounded-2xl border border-slate-900/10"><table className="w-full text-left text-sm"><caption className="p-4 text-left font-bold">Assumption-based monthly outlook</caption><thead className="bg-slate-50"><tr>{["Month", "Revenue", "Baseline costs", "Scenario costs", "Scenario profit", "Scenario cash"].map(label => <th className="whitespace-nowrap p-3" key={label}>{label}</th>)}</tr></thead><tbody>{projection.rows.map(r => <tr className="border-t border-slate-900/10" key={r.month}><th className="whitespace-nowrap p-3">{r.label}</th>{[r.revenue, r.baseCosts, r.scenarioCosts, r.scenarioProfit, r.scenarioCash].map((value, i) => <td key={i} className="whitespace-nowrap p-3">{money(value)}</td>)}</tr>)}</tbody></table></div>
            <section className="mt-6 rounded-2xl border border-slate-900/10 p-5">
              <h3 className="text-xl font-semibold">Best, expected, and worst case</h3>
              <p className="mt-3 text-sm leading-6 text-slate-600">Expected uses your current scenario. Best raises each month's revenue and lowers costs; worst does the reverse. These level changes apply once to each projected month, without changing the growth rates.</p>
              <div className="mt-4 grid gap-4 sm:grid-cols-2"><Control label="Revenue variation (%)" value={revenueSwing} min={0} max={50} onChange={setRevenueSwing} /><Control label="Cost variation (%)" value={costSwing} min={0} max={50} onChange={setCostSwing} /></div>
              <div className="mt-5 grid gap-3 md:grid-cols-3">{cases.map(c => <article key={c.name} className={`min-w-0 rounded-2xl p-5 ${c.name === "Expected case" ? "bg-slate-900 text-white" : "bg-slate-50"}`}><h4 className="font-semibold">{c.name}</h4><p className="mt-3 text-2xl font-semibold">{money(c.totalProfit)}</p><p className="mt-1 text-sm">Total operating profit · {settings.horizon} months</p><p className="mt-4 text-sm leading-6">{forecastMonth(inputs.reportingPeriod, settings.horizon)} profit: <strong>{money(c.final.profit)}</strong><br />Ending cash: <strong>{money(c.final.cash)}</strong></p><p className="mt-3 text-sm leading-6">{c.firstShortfall ? `First cash shortfall: ${forecastMonth(inputs.reportingPeriod, c.firstShortfall)}.` : "No projected cash shortfall in this horizon."}</p></article>)}</div>
              <p className="mt-4 text-sm leading-6 text-slate-600">The variation percentages are adjustable stress-test assumptions. They are not statistical confidence intervals or likelihoods. Cash uses the same collection and payment assumptions as the monthly outlook.</p>
            </section>
            <section className="mt-6 rounded-2xl border border-slate-900/10 p-5">
              <h3 className="text-xl font-semibold">Ask about your numbers</h3>
              <p className="mt-3 text-sm leading-6 text-slate-600">Calculated from the current monthly baseline. Review complete costs and the reporting period before making a decision.</p>
              <div className="mt-4 flex flex-wrap gap-2">{([{ id: "spending", label: "Where am I overspending?" }, { id: "drop", label: "What if revenue drops 15%?" }, { id: "hire", label: "Can I cover another employee?" }] as const).map(q => <button key={q.id} aria-pressed={question === q.id} className={`rounded-2xl px-4 py-3 text-sm font-bold ${question === q.id ? "bg-slate-900 text-white" : "border border-slate-900/15"}`} onClick={() => setQuestion(q.id)}>{q.label}</button>)}</div>
              {question === "hire" ? <div className="mt-4 max-w-sm"><Control label="Full monthly employment cost ($)" value={hireCost} min={0} max={1e9} onChange={setHireCost} hint="Include wages, employer taxes, benefits, and other incremental costs." /></div> : null}
              <div role="status" className="mt-5 rounded-2xl bg-slate-50 p-5 leading-7">
                {question === "spending" ? analysis.directLeakTotal > 0 ? <p>Your entered spending exceeds your entered category targets by <strong>{money(analysis.directLeakTotal)} this month</strong>. {analysis.leaks.filter(l => l.type === "direct").slice(0, 3).map(l => `${l.name}: ${money(l.amount)} above target.`).join(" ")} Check activity, invoice timing, and budget assumptions before treating the difference as avoidable waste.</p> : <p>No overrun was detected against the targets entered. Categories without targets are excluded; this does not establish that all spending is efficient.</p> : question === "drop" ? <p>A one-time 15% revenue drop takes monthly revenue from {money(inputs.revenue)} to <strong>{money(inputs.revenue * 0.85)}</strong>. Holding entered costs at {money(analysis.totalExpenses)}, operating profit becomes <strong>{money(inputs.revenue * 0.85 - analysis.totalExpenses)}</strong>. This assumes unchanged costs and excludes taxes, debt service, and unentered items.</p> : hireCost <= 0 ? <p>Enter the full monthly employment cost to compare it with operating profit.</p> : <p>Current entered operating profit is {money(analysis.operatingProfit)}. Adding {money(hireCost)} in monthly employment costs leaves <strong>{money(analysis.operatingProfit - hireCost)}</strong>, assuming unchanged revenue and other costs. {analysis.operatingProfit - hireCost < 0 ? "The entered baseline would show an operating loss." : "The entered baseline covers this cost, but collection timing, reserves, and missing costs still matter."} No additional sales from the new employee are assumed.</p>}
              </div>
            </section>
            <button className="mt-4 inline-flex items-center gap-2 rounded-xl border border-slate-900/15 px-5 py-3 text-sm font-bold" onClick={download}><Download size={16} /> Download forecast & assumptions</button>
          </>}
          <p className="mt-5 text-sm leading-6 text-slate-600">This is a planning scenario. Cash assumes revenue is collected and operating costs are paid in the same month, plus your net cash adjustments. It does not model receivables, payables, seasonality, or unentered costs. Alerts update while this workspace is open; they are not email or background notifications.</p>
          <details className="mt-6 rounded-2xl border border-slate-900/10 p-5"><summary className="font-semibold">Use your historical monthly trend</summary><p className="mt-3 text-sm leading-6 text-slate-600">Add at least three consecutive, comparable months with positive revenue and expenses. PulseIQ calculates the geometric average growth from the first to the last month. Applying the rates keeps your current diagnostic as the starting amount; confirm it represents the latest comparable month.</p>
            <div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm font-bold">Month<input aria-label="Historical month" className="mt-2 w-full rounded-xl border border-slate-900/15 p-3" type="month" value={month} onChange={e => setMonth(e.target.value)} /></label><Control label="Historical revenue ($)" value={historicalRevenue} min={0} max={1e9} onChange={setHistoricalRevenue} /><Control label="Historical operating costs ($)" value={historicalExpenses} min={0} max={1e9} onChange={setHistoricalExpenses} /></div><button className="mt-4 rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white" onClick={() => { if (!month || historicalRevenue <= 0) { setMessage("Choose a valid month and enter positive historical revenue."); return; } const next = normalizeHistory([...history.filter(r => r.month !== month), { month, revenue: historicalRevenue, expenses: historicalExpenses }]); if (next.length > 24 || !next.some(r => r.month === month)) { setMessage("Use valid figures and no more than 24 months."); return; } setHistory(next); setMessage("Historical month added or replaced. Save the plan to keep it."); }}>Add / replace month</button>
            {history.map(r => <div className="mt-3 flex flex-wrap justify-between gap-2 border-t border-slate-900/10 pt-3 text-sm" key={r.month}><span>{r.month} · Revenue {money(r.revenue)} · Costs {money(r.expenses)}</span><button className="font-bold underline" aria-label={`Remove ${r.month}`} onClick={() => setHistory(rows => rows.filter(row => row.month !== r.month))}>Remove</button></div>)}
            {trend ? <div className="mt-4"><p className="text-sm">{trend.months} comparable months: revenue {trend.revenueGrowth}% / month; operating costs {trend.expenseGrowth}% / month.</p><button className="mt-3 rounded-xl border border-slate-900/15 px-4 py-2 text-sm font-bold" onClick={() => { setSettings(s => ({ ...s, revenueGrowth: trend.revenueGrowth, expenseGrowth: trend.expenseGrowth })); setMessage("Historical rates applied. Check that the diagnostic starting amounts match the latest comparable month."); }}>Apply historical growth rates</button></div> : <p className="mt-4 text-sm text-slate-600">A usable trend requires 3–24 consecutive months with positive revenue and costs, and monthly growth between −50% and 50%.</p>}
          </details>
        </div>
      </div>
    </div>
    {message ? <p role="status" className="mt-5 rounded-xl bg-slate-100 p-4 text-sm font-bold">{message}</p> : null}
  </section>;
}
